language: python

python:
  - "2.7"
  - "3.2"
  - "3.4"

env:
  - DJANGO=django==1.5.10
install:
  - pip install $DJANGO
  - pip install -r requirements/travis-ci.txt

script:
  - python runtests.py

branches:
    only:
        - master

matrix:
  include:
    - python: "2.7"
      env: DJANGO=django==1.6.6
    - python: "2.7"
      env: DJANGO=django==1.7
    - python: "3.2"
      env: DJANGO=django==1.7
    - python: "3.4"
      env: DJANGO=django==1.7
  exclude:
    - python: "3.2"
      env: DJANGO=django==1.5.10 --use-mirrors
    - python: "3.4"
      env: DJANGO=django==1.5.10 --use-mirrors
